;;; custom.el autogenerated by emacs -*- lexical-binding: t; -*-
;;; doesn't edit this file by hand if its unnecessary; loaded by init.el.

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages nil)
 '(safe-local-variable-values
   '((eval add-hook 'after-save-hook
           (lambda nil
             (when
                 (and buffer-file-name
                      (string-suffix-p ".org" buffer-file-name)
                      (string-prefix-p
                       (expand-file-name user-emacs-directory)
                       (expand-file-name buffer-file-name)))
               (org-babel-tangle)))
           nil t))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
